apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: ns-dev
spec:
  hard:
    pods: "10"
    requests.cpu: "2000m"
    requests.memory: "2Gi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
