apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: ns-prod
spec:
  hard:
    requests.cpu: "4000m"
    requests.memory: "4Gi"
    limits.cpu: "4000m"
    limits.memory: "4Gi"
